### PR TITLE
fix cap spar weight; cmac calculation

### PR DESCRIPTION
**Pull request by mjburton11**

### CODE REVIEW

**Comment by mjburton11** [comment]
@bqpd is it possible to set up the integrated testing yet for PRs? I don't want to merge and then break everything, like I may have accidentally done on jho...

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
add to whitelist

**Comment by mjburton11** [comment]
sweet! this is dope!

**Comment by bqpd** [comment]
(had a bug in the jenkins script)

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
retest this please

**Comment by bqpd** [comment]
test models please

**Comment by mjburton11** [comment]
Do you have to say "test models please" to get this to retest?

**Comment by bqpd** [comment]
yup! my thinking was that eventually there'll be a regular library test which can be tested separately (since it won't require importing every dang thing)

**Comment by mjburton11** [comment]
haha that was smart

**Comment by bqpd** [comment]
the email was probably from an earlier test

**Comment by mjburton11** [comment]
test this please

**Comment by mjburton11** [comment]
test models please

**Comment by mjburton11** [comment]
@bqpd this failed due to a turbofan model failing.  But I don't think that depends on gpkitmodels... It also only failed on Windows...

**Comment by mjburton11** [comment]
test models please

**Comment by mjburton11** [comment]
test models please

**Comment by bqpd** [comment]
Weird, why is this PR showing as making no changes?

**Comment by mjburton11** [comment]
woah, yeah what is going on?

**Comment by mjburton11** [comment]
also why did it magically past tests all of a sudden?

**Comment by bqpd** [comment]
the turbofan failure is a sometimes thing.

**Comment by bqpd** [comment]
the no-changes is confirmed on my local git

**Comment by mjburton11** [comment]
I did an update branch.. would that have changed it?

**Comment by bqpd** [comment]
naw, the previous commit also had no changes...confirmed by checking the file on master. What changes should this be making?

**Comment by mjburton11** [comment]
It was supposed to update an incorrect constraint in capspar and fix a bad substitution

**Comment by mjburton11** [comment]
If you look at the commits on this PR I clearly changes so...

**Comment by bqpd** [comment]
But all the changes they make are already in master

**Comment by mjburton11** [comment]
If I checkout 3e26eb599100070cb744dde348b32ff2caa1a55f, it has all the changes that I expect

**Comment by bqpd** [comment]
I think your earlier commit titled `fix merge` might have been the reversion?

**Comment by mjburton11** [comment]
Oh..... yeah, my bad

**Comment by mjburton11** [comment]
So should I just delete this PR?

**Comment by bqpd** [comment]
probably...

**Pull request closed without merging**
